import React from 'react'

const Lazy = () => {
  return (
    <div>
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading
        hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading hello this is lazyloading
    </div>
  )
}

export default Lazy